### ISSUE TITLE
Icon doesn't show up 

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/org.claws_mail.Claws-Mail#2]
https://flathub.org/apps/details/org.claws_mail.Claws-Mail

Please also remove the icon cache file. It's generated on the user's system and should not be shipped here.

Also, please install the appdata file only once in metainfo https://github.com/flathub/org.claws_mail.Claws-Mail/blob/master/org.claws_mail.Claws-Mail.json#L243-L244
no need to install it on appdata folder too.

The icons seems to be installed using a different icon name, it should use the app-id and you will probably need to patch the desktop file too. You can use the rename-icon & copy-icon properties of the flatpak manifest.

**Comment by cobratbq** [comment]
> Please also remove the icon cache file. It's generated on the user's system and should not be shipped here.

Done.

> Also, please install the appdata file only once in metainfo https://github.com/flathub/org.claws_mail.Claws-Mail/blob/master/org.claws_mail.Claws-Mail.json#L243-L244
no need to install it on appdata folder too.

Done. I wasn't sure as different packages have different approaches (apparently).

> The icons seems to be installed using a different icon name, it should use the app-id and you will probably need to patch the desktop file too. You can use the rename-icon & copy-icon properties of the flatpak manifest.

Desktop icon (finally) fixed. I haven't used `rename-icon` or `copy-icon`. I think it would help if you do a quick check and let me know if things can be improved. Right now I've copied the desktop file from the claws-mail package after build, so a little bit of redundancy.

**Comment by bilelmoussaoui** [comment]
You could use desktp-file-edit to edit the desktop file on post-install. See https://github.com/flathub/com.github.optyfr.JRomManager/blob/0b1681e54b2aa2ecf5d6bc3d5724f6cae4d2e67b/com.github.optyfr.JRomManager.yaml#L30
 
Your current patch is not working as it's applied to the desktop file from the debian package but you're installing the destkop file shipped in this repository. 

What you will need to do:
- Remove the desktop file shipped in this repo
- Use rename-desktop-file
- Patch the installed desktop file to use the new icon name or just use rename-icon & copy-icon.

**Comment by cobratbq** [comment]
> Your current patch is not working as it's applied to the desktop file from the debian package but you're installing the destkop file shipped in this repository.

Is there a build log where I can see results? For me, locally, the patch is applied to the desktop-file I just committed in the repo. (Building the package fails now that I removed it.)

**Comment by bilelmoussaoui** [comment]
In that case, just remove the patch and apply it directly the shipped desktop file.

**Comment by bilelmoussaoui** [comment]
Also, you can use merge requests to trigger bot builds & ensure things are working before publishing directly.

**Comment by bilelmoussaoui** [comment]
The icon shows up correctly now. Thansk!
It would be nice if we could update those pre 2000 screenshots if possible

**Comment by cobratbq** [comment]
> It would be nice if we could update those pre 2000 screenshots if possible

@bilelmoussaoui That is still an item I intend to fix. Also the resolutions are wrong. How strict are the expectations of using a 16:9 ratio resolution? (Because a compose window wouldn't look very nice with such a ration.)

**Comment by bilelmoussaoui** [comment]
I have never used the 16:9 ratio myself on my apps, just make sure the screenshots are up to date so the user gets what he sees on the screenshots.
