### ISSUE TITLE
Cannot install flatpak, maximum size issue reported

### ISSUE THREAD

**Issue by shoop** [flathub/org.claws_mail.Claws-Mail#30]
I cannot install Claws Mail from flathub on my fresh installed Fedora Silverblue 37 system:

```
stijn@tangaloor: ~
$ flatpak install flathub org.claws_mail.Claws-Mail
Looking for matches…

org.claws_mail.Claws-Mail permissions:
    ipc      network      pcsc      wayland     x11     file access [1]     dbus access [2]     system dbus access [3]

    [1] home, xdg-run/gnupg:ro
    [2] org.freedesktop.Notifications
    [3] org.freedesktop.NetworkManager


        ID                                  Branch          Op          Remote           Download
 1. [✗] org.claws_mail.Claws-Mail           stable          i           flathub          3,4 MB / 19,9 MB

Error: While pulling app/org.claws_mail.Claws-Mail/x86_64/stable from remote flathub: URI https://dl.flathub.org/repo/deltas/X8/Ybue5CtWrVLKJLskvZQ9ZAxvnpCAsfaah5yxGBHEk/1 exceeded maximum size of 1026305 bytes
error: Failed to install org.claws_mail.Claws-Mail: While pulling app/org.claws_mail.Claws-Mail/x86_64/stable from remote flathub: URI https://dl.flathub.org/repo/deltas/X8/Ybue5CtWrVLKJLskvZQ9ZAxvnpCAsfaah5yxGBHEk/1 exceeded maximum size of 1026305 bytes
stijn@tangaloor: ~
$ curl -slo - https://dl.flathub.org/repo/deltas/X8/Ybue5CtWrVLKJLskvZQ9ZAxvnpCAsfaah5yxGBHEk/1 | wc -c
1026433
```

Other flatpaks installed just fine. Possibly it is an upstream issue but I was not sure where else to report this. Happy to push this further upstream given some direction.

**Comment by shoop** [comment]
This resolved itself somehow. Again, I'm happy to push this upstream if I would know where to start. In the meantime, consider it closed again.

**Comment by cobratbq** [comment]
hi, sorry for the late follow-up. I have never encountered this issue before. Given that files are hosted on flathub, it may be an issue on their side, as-in claws-mail is not even a significant factor.

Please let me know if this happens again specifically for claws-mail.

**Comment by shoop** [comment]
No problem, seeing as I can't reproduce anyhow. For the record, I did not have any issue with downloading other Flatpaks at the time I saw this problem.

Thanks for your work on claws-mail!
